CONFIG_ZMK_KEYBOARD_NAME="ZEN"
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_CDC_ACM_BOOTLOADER_TRIGGER=y
CONFIG_ZMK_STATUS_LED=y
CONFIG_ZMK_IDLE_TIMEOUT=300000
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=9000000
CONFIG_ZMK_NON_LIPO_MIN_MV=1000
CONFIG_ZMK_NON_LIPO_LOW_MV=900
CONFIG_ZMK_POINTING_SMOOTH_SCROLLING=y
CONFIG_INPUT_THREAD_STACK_SIZE=4096
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5

# 自動補正
CONFIG_PMW3610_ALT_SMART_ALGORITHM=n

# PCとの通信スピード
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=12

# 左右間の通信スピード（左手からのデータ受け取り用）
CONFIG_ZMK_SPLIT_BLE_CENTRAL_INTERVAL_MIN=6
CONFIG_ZMK_SPLIT_BLE_CENTRAL_INTERVAL_MAX=6
